name: shaker
description: Easy-to-use Flutter widget to shake any child widget with customizable duration, frequency, rotation, offset, and curve.
issue_tracker: https://github.com/SoundSliced/shaker/issues
repository: https://github.com/SoundSliced/shaker
version: 2.1.0
homepage: https://github.com/SoundSliced/shaker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
